/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingsRouteImport } from './routes/writings'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as UsesRouteImport } from './routes/uses'
import { Route as SpeakingRouteImport } from './routes/speaking'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WritingsRoute = WritingsRouteImport.update({
  id: '/writings',
  path: '/writings',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsesRoute = UsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coaching': typeof CoachingRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/speaking': typeof SpeakingRoute
  '/uses': typeof UsesRoute
  '/videos': typeof VideosRoute
  '/writings': typeof WritingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coaching': typeof CoachingRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/speaking': typeof SpeakingRoute
  '/uses': typeof UsesRoute
  '/videos': typeof VideosRoute
  '/writings': typeof WritingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coaching': typeof CoachingRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/speaking': typeof SpeakingRoute
  '/uses': typeof UsesRoute
  '/videos': typeof VideosRoute
  '/writings': typeof WritingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coaching'
    | '/contact'
    | '/projects'
    | '/speaking'
    | '/uses'
    | '/videos'
    | '/writings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coaching'
    | '/contact'
    | '/projects'
    | '/speaking'
    | '/uses'
    | '/videos'
    | '/writings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coaching'
    | '/contact'
    | '/projects'
    | '/speaking'
    | '/uses'
    | '/videos'
    | '/writings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoachingRoute: typeof CoachingRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  SpeakingRoute: typeof SpeakingRoute
  UsesRoute: typeof UsesRoute
  VideosRoute: typeof VideosRoute
  WritingsRoute: typeof WritingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writings': {
      id: '/writings'
      path: '/writings'
      fullPath: '/writings'
      preLoaderRoute: typeof WritingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uses': {
      id: '/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof UsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoachingRoute: CoachingRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  SpeakingRoute: SpeakingRoute,
  UsesRoute: UsesRoute,
  VideosRoute: VideosRoute,
  WritingsRoute: WritingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
